title:  David Brandfonbrener
author:
  name: 'David Brandfonbrener'

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'learning-4'

google-ID: 'UA-190570049-1'

menu:
- {name: 'home', url: '/'}
- {name: 'papers', url: '/menu/papers.html'}
- {name: 'blog', url: '/menu/blog.html'}
# - {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://github.com/davidbrandfonbrener'}
#- {icon: 'twitter', link: 'https://twitter.com/wfwhitney'}
- {icon: 'envelope', link: 'mailto:david.brandfonbrener@nyu.edu'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
